spring:
  profiles:
    active: local

  jpa:
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  thymeleaf:
    cache: false #캐싱 끄기 개발시에만
