spring.application.name=boardserver
# mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/test
spring.datasource.username=test
spring.datasource.password=test1234
mybatis.mapper-locations=classpath:com.largyborad.boardserver.mapper/*.xml